services:
  bot:
    build: .
    volumes:
      - ./.env:/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ambient_db
      POSTGRES_USER: antonmiklis
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
